#!/usr/bin/env bash

packages=(
    qemu-system
    libvirt-daemon-system
    libvirt-clients
    bridge-utils
    virt-manager
    qemu-guest-agent
)

sudo apt install -y "${packages[@]}"

# Add user to groups
user="$USER"
sudo adduser "$user" libvirt
sudo adduser "$user" kvm

# Enable virtualisation daemon
sudo systemctl enable libvirtd
