#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"
system_task="./tasks/system"

while [[ $# > 0 ]]; do
    if [[ $1 == "--dry" ]]; then
        dry="1"
    else
        filter="$1"
    fi

    shift
done

log() {
    if [[ $dry == "1" ]]; then
        echo "[DRY_RUN]: $@"
    else
        echo "$@"
    fi
}

execute() {
    log "execute $@"

    if [[ $dry == "1" ]]; then
        return
    fi

    "$@"
}

filter() {
    log "filtering $1"

    if echo "$1" | grep -qv "$1"; then
        log "filtering $1"
        return 1
    fi

    return 0
}

log "$script_dir -- $filter"

if ! filter "$system_task"; then
    execute $system_task
fi

cd $script_dir
scripts=$(find ./tasks -maxdepth 1 -mindepth 1 -executable -type f -not -path "$system_task")
echo $scripts

for script in $scripts; do
    if filter "$script"; then
        continue
    fi

    execute $script
done
