#!/usr/bin/env bash

dir="$GITHUB_DIR/dwmblocks-async"

if [[ -d $dir ]]; then
    sudo rm $dir/config.h
else
    git clone git@github.com:dnlznk/dwmblocks-async $dir
fi

cd $dir
sudo make clean install
cd -
