#!/usr/bin/env bash

target="/etc/apt/keyrings/githubcli-archive-keyring.gpg"
out=$(mktemp)

wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg
cat $out | sudo tee $target > /dev/null
sudo chmod go+r $target
sudo mkdir -p -m 755 /etc/apt/sources.list.d
echo "deb [arch=$(dpkg --print-architecture) signed-by=$target] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

sudo apt update
sudo apt install gh -y
