#!/usr/bin/env bash

# Create github directory
if [[ ! -d "$GITHUB_DIR" ]]; then
    mkdir -p "$GITHUB_DIR"
fi

# Packages to install
packages=(
    zsh
    tmux
    i3
    picom
    xorg
    xinit
    lightdm
    alsa-utils
    pulseaudio
    pulseaudio-module-bluetooth
    stow
    tldr
    libx11-dev
    gcc
    valgrind
    build-essential
    libxft-dev
    gawk
    fd-find
    ripgrep
    ninja-build
    gettext
    cmake
    unzip
    curl
    gpg
    mokutil
    qemu-system
    libvirt-daemon-system
    libvirt-clients
    bridge-utils
    virt-manager
    qemu-guest-agent
    pass
    ufw
    dkms
    fswatch
    ntfs-3g
    fuse3
    fwupd
    polybar
    luarocks
    python3.11-venv
    ffmpeg
    vlc
    mpv
    imagemagick
    inotify-tools
    slick-greeter
    feh
    bc
    genisoimage
    network-manager
    rofi
    maim
    xdotool
    libsecret-1-dev
    jq
    libcunit1-dev
    sqlite3
    libsqlite3-dev
    libimlib2-dev
    libxcb-util-dev
    acpid
    lm-sensors
    iw
    pinentry-gtk2
    xbacklight
)

# Update system and install packages
sudo apt update
sudo apt install -y "${packages[@]}"

# Activate firewall
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

# Set lightdm as default display manager
sudo dpkg-reconfigure lightdm

# Add user to groups
user="$USER"
sudo adduser "$user" libvirt
sudo adduser "$user" kvm

# Enable virtualisation daemon
sudo systemctl enable libvirtd

# Set zsh as default shell
sudo chsh -s $(which zsh) $user

# Hide default option in lightdm
echo "Hidden=true" | sudo tee /usr/share/xsessions/lightdm-xsession.desktop

# Get dotfiles
dotfiles_dir=$HOME/.dotfiles
if [[ -d "$dotfiles_dir" ]]; then
    exit 0
fi

source <(gpg -d $(pwd)/vars/secrets 2> /dev/null)

git clone "https://oauth2:$gh_pat@github.com/dnlznk/.dotfiles" $dotfiles_dir
cd $dotfiles_dir
git remote remove origin
git remote add origin "git@github.com:dnlznk/.dotfiles"

rm $HOME/.zshenv

./linux

sudo mkdir -p /usr/share/backgrounds
sudo cp wallpaper/tropical-beach.jpg /usr/share/backgrounds/tropical-beach.jpg

sudo rm /etc/lightdm/lightdm.conf
sudo ln -s lightdb/lightdm.conf /etc/lightdm/lightdm.conf
sudo ln -s lightdm/slick-greeter.conf /etc/lightdm/lightdm.conf

source zsh/.config/zsh/zsh-functions
source zsh/.config/zsh/zsh-exports

mkdir -p $create_dir
cp "$secrets_dir/one" $secret_one_dest
cp "$secrets_dir/two" $secret_two_dest
chmod "0600" $secret_two_dest
cp "$secrets_dir/three" $secret_three_dest
cp "$secrets_dir }}/four" $secret_four_dest
chmod "0600" $secret_four_dest
cp "$secrets_dir/five" $secret_five_dest
cp "$secrets_dir/six" $secret_six_dest
chmod "0600" $secret_six_dest
cp "$secrets_dir/seven" $secret_seven_dest

mkdir -p $key_dir
cp "$secrets_dir/eight" $key_one_dest
cp "$secrets_dir/nine" $key_two_dest

git clone git@github.com:dnlznk/pass-store $PASSWORD_STORE_DIR
git git@github.com:dnlznk/notes $HOME/Documents/Notes

cd -
